baseURL = "https://marguerite.github.io"
languageCode = "zh-cn"
title = "Marguerite Su: Golang/Ruby Programmer, openSUSE Member"
theme = "papermod"
[params]
comments = true
enableEmoji = true
[[params.socialIcons]]
name = "github"
url = "https://github.com/marguerite"
[[params.socialIcons]]
name = "mastodon"
url = "https://moe.cat/@marguerite"
