baseURL = "https://marguerite.github.io"
languageCode = "zh-cn"
title = "Marguerite Su: Golang/Ruby Programmer, openSUSE Member"
theme = "blank"
disqusShortname = "innamoramento"
pygmentsCodefences = true
pygmentsStyle = "github"
